language: node_js

node_js:
  - "12.16.1"

cache:
  directories:
    - node_modules

script:
    - npm install -g codecov
    - npm test && codecov
    - npm run build
    - npm run docs

deploy:
  provider: pages
  skin-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master