language: node_js

node_js:
  - "12.16.1"

cache:
  directories:
    - node_modules

before_install:
    - sudo apt-get update
    - sudo apt-get -y install ruby openjdk-8-jre

script:
    - npm install -g codecov
    - npm test && codecov
    - npm run build

deploy:
  provider: pages
  skin-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master